version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-fastapi
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blog_db
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
    name: mysql-fastapi_data